#db de usuarios
spring:
  datasource: 
    url: jdbc:oracle:thin:@172.15.9.85:1521:ORACLEDE
    username: scott
    password: tiger
  jpa.hibernate.ddl-auto: update
  mail: 
    host: 172.15.2.32
    port: 25
    #ssl=false
  mvc.favicon.enabled: false
  
server:
  port: 9999
  contextPath: /uaa
  
logging.level.root: DEBUG
    
debug: true